### ISSUE TITLE
How to set public_key programmatically?

### ISSUE THREAD

**Issue by hitesh-banknovo** [plaid/plaid-link-android#10]
Please provide a way to set public key (public_key ) to initialize Plaid SDK programmatically. 

FYI exception  **_Please provide the public key in a manifest metadata tag with the android:name="com.plaid.link.public_key"_**

**Comment by zsweigart** [comment]
Thanks for the request, we'll open a ticket to add this functionality.

**Comment by hitesh-banknovo** [comment]
Thanks for the prompt reply. Will waiting for the next update on it.

**Comment by zsweigart** [comment]
Release 0.3.0 is now available, you can set the key programmatically in `Plaid.create` call by using `PlaidOptions`

In Java:
```
PlaidOptions.Builder()
      .publicKey("YOUR KEY")
      .build();
```

In Kotlin:
```
PlaidOptions(publicKey =  "YOUR KEY")
```

**Comment by hitesh-banknovo** [comment]
Thanks, Resolved.
