### ISSUE TITLE
Reauthenticate Chase Failed in sanbox

### ISSUE THREAD

**Issue by siliconprime-van** [plaid/plaid-link-android#117]
Hello,

I am using Android SDK version 3.1.1:
issue: can not reauthenticate failed after force a given Item into an ITEM_LOGIN_REQUIRED state.

steps: (I am using Sanbox)
1. link Chase success
2. Force an Item into an error state ITEM_LOGIN_REQUIRED by using /sandbox/item/reset_login
3. reauthenticate this Item by choosed "Grant access" and the SDK run into linkExit event

here is my link_token: "link-sandbox-69d45059-d1d3-40b5-aa79-226c31fbda7c"

Please help me check! it very urgent.

Many thanks,
Van

**Comment by JeroenMols** [comment]
Hi @siliconprime-van ,

Thanks for filing this issue!

I'm unfortunately not yet able to reproduce your issue. Here's the steps that I'm using:

1. Create a `link_token` using `link/token/create` (auth as product)
1. Open link, agree, choose chase, grant access, get `public_token`
1. Exchange `public_token` for `access_token` using `item/public_token/exchange`
1. Reset login with `access_token`using `sandbox/item/reset_login`
1. Create new `link_token` from `access_token` (using client_id, secret and link_token)
1. Open link, agree, choose chase, grant access -> works

Could you please share a more detailed version of your steps?

A colleague of mine did see something similar and she was wondering whether it worked on our development environment (not sandbox).

Thank you!
Jeroen

**Comment by JeroenMols** [comment]
Hi @siliconprime-van ,

We've noticed that this is currently broken on our sandbox environment. Both development and production environment are unaffected. We're working to roll out a fix to sandbox soon, which shouldn't require any changes from your end.

I'll keep you posted on the sandbox fix!

Warm regards,
Jeroen

**Comment by amytang0** [comment]
Hi @siliconprime-van ,

Could you try again with our newest version [`3.2.0-rc2`](https://bintray.com/plaid/link-android/com.plaid.link/3.2.0-rc2)? 

FYI: We will release 3.2.0 officially in a few days, so that you won't need to be on an RC for too long.

Thanks!
Amy

**Comment by ballerboiiii** [comment]
Help me through this

**Comment by JeroenMols** [comment]
Hi @siliconprime-van,

Our `3.2.0` release is now public, so you no longer have to rely on an RC.
https://bintray.com/plaid/link-android/com.plaid.link/3.2.0

Thanks for letting us know whether this resolves your issue or not.

Jeroen

**Comment by JeroenMols** [comment]
Hi @siliconprime-van,

We haven't heard back from you in a while, so we're going to assume that you've managed to resolve the issue on your end.
Please feel free to reopen/file a new ticket should that not be the case.

Thanks again for filing this issue!
Jeroen
