### ISSUE TITLE
Plaid Android SDK

### ISSUE THREAD

**Issue by hardikdhola** [plaid/plaid-link-android#12]
- i used the following code but when i tap on **CONTINUE** button on last screen of Plaid then  "onActivityResult()" is not calling. see below image.
- so how can i check Plaid Success response and linked bank account informations?.

![device-2019-12-11-123443](https://user-images.githubusercontent.com/47768773/70599235-aa472600-1c12-11ea-87b5-1693f19e15dc.png)

//////////////////////
val intent = Intent(this, LinkActivity::class.java)
intent.putExtra( Plaid.LINK_CONFIGURATION,
LinkConfiguration( 
clientName = "App Name",
products = listOf(PlaidProduct.AUTH),
webviewRedirectUri = "myapp://redirect") ) 
startActivityForResult(intent, LINK_REQUEST_CODE)
/////////////////////

**Comment by keyurbelani** [comment]
I also faces the same Issue with plaid sdk version - 0.3.0

After click on "Continue", I got callback with onActivityResult() with resultCode=0

I created only one Activity as "MainActivity" and use this with RedirectLinkActivity.

===== AndroidManifest.xml =====

<activity android:name=".MainActivity" android:launchMode="singleInstance">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="plaid-redirect"
                    android:scheme="plaidtestapp" />
            </intent-filter>
        </activity>
        <activity android:name="com.plaid.link.LinkActivity" /> 


===== MainActivity.kt =====

val intent = Intent(this, LinkActivity::class.java)
                intent.putExtra( Plaid.LINK_CONFIGURATION,
                    LinkConfiguration(
                        // required
                        clientName = "SimplyPay App",
                        products = listOf(PlaidProduct.TRANSACTIONS),
                        webviewRedirectUri = "plaidtestapp://plaid-redirect",
                        // optional
                        environment = PlaidEnvironment.SANDBOX, // Defaults to plaid options value if set or SANDBOX
                        language = Locale.ENGLISH.language, // Defaults to English
                        countryCodes = listOf(Locale.US.country), // Defaults to US
                        webhook = "https://requestb.in",
                        userEmailAddress = "{registered email id}",
                        userLegalName = "{registered email id}",
                        userPhoneNumber = "{phone number}") )
                startActivityForResult(intent, LINK_REQUEST_CODE)


Thanks in Advance.

**Comment by rajkumarsavu** [comment]
I am also getting same issues after update to new SDK 
-->implementation 'com.plaid.link:sdk-core:0.3.0'
please help me out

**Comment by AanalShah** [comment]
> I am also getting same issues after update to new SDK
> -->implementation 'com.plaid.link:sdk-core:0.3.0'
> please help me out

implementation 'com.plaid.link:sdk-core:0.3.1
update 0.3.0 to 0.3.1

**Comment by keyurbelani** [comment]
> I am also getting same issues after update to new SDK
> -->implementation 'com.plaid.link:sdk-core:0.3.0'
> please help me out

@rajkumarsavu @hardikdhola 

Please update plaid sdk version to 0.3.1.

```
dependencies {
  implementation 'com.plaid.link:sdk-core:0.3.1'
}
```

It solved callback issue perfectly, I tested it.

**Comment by amytang0** [comment]
Please update to `implementation 'com.plaid.link:sdk-core:0.3.1'`
