### ISSUE TITLE
[Feature Request] Guidance regarding ActivityResult API

### ISSUE THREAD

**Issue by JvmName** [plaid/plaid-link-android#125]
Currently (`3.2.2`), `PlaidHandler.open` calls `startActivityForResult` under the hood, meaning that it generates the intent itself. This also means that the result is handed through `Fragment#onActivityResult`. 

Unfortunately, this means that callers using `androidx.fragment:fragment:1.3.0-rc01` (which will likely land in stable some time early Q1) see that `onActivityResult` is deprecated. 
It also mucks up my flow, since `onActivityResult` is much harder to wrap with Coroutines versus `registerForActivityResult` 😁 

I understand that the `startActivityForResult` flow load-bearing for existing users; is it possible to add another path? Maybe Plaid could implement its own [ActivityResultContract](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContract) that could be handed to the `register` call? (I assume there's good reason for obfuscating the actual Intent process, but exposing the Intent would also allow users to choose how to receive the callback)

**Comment by amytang0** [comment]
Thanks for the suggestion! Definitely looking into `ActivityResultContract` in 2021 and will keep you posted.

Happy Holidays!

**Comment by JvmName** [comment]
Many thanks and happy holidays!

**Comment by amytang0** [comment]
Keeping you updated, we have a tentative PR up to support this; we're just waiting on `androidx.fragment:fragment:1.3.0` to stabilize.

**Comment by amytang0** [comment]
Hey hey, since `androidx.fragment:fragment:1.3.0` stabilized, we're going to be releasing the `LinkActivityResultContract` in our next release `3.2.4` (~Feb 16 2021). We will release an example using the new `ActivityResultContract`, but please feel free to give us feedback! Thanks yall

**Comment by amytang0** [comment]
3.2.4 is out!

**Comment by JeroenMols** [comment]
Here's more information about the new API: https://github.com/plaid/plaid-link-android/releases/tag/3.2.4
We would very much welcome your feedback!
