### ISSUE TITLE
Is there a way to indicate which accounts were already added?

### ISSUE THREAD

**Issue by shalbert94** [plaid/plaid-link-android#126]
More of a feature request than a bug.

Our app wants users to connect all of their financial accounts. To help users with connecting multiple accounts, it would be helpful if there's a way to indicate which accounts have been connected while the user is in the Link flow. This way we don't risk irritating a user because they tried adding an account that was already added. Is there something in the works to help with this case?

**Comment by amytang0** [comment]
We are unsure of what accounts a user has connected at least until either 1. their credentials are inputted or 2. you have opted into the [returning user experience](https://plaid.com/docs/link/returning-user/).

We have some tips available to prevent creating duplicate account connections: https://plaid.com/docs/link/duplicate-items/

**Comment by shalbert94** [comment]
Is there clearer documentation about the [Returning User Experience](https://plaid.com/docs/link/returning-user/) (RUX)? It's unclear how the pre-matched and pre-authenticated experiences work, nor is it clear what they look like.

If it's one of those "just implement it, and you'll see" cases, I can implement it. However, it would be helpful if the RUX had more comprehensive documentation.

**Comment by shalbert94** [comment]
Following up

**Comment by shalbert94** [comment]
@amytang0, are you able to provide a response?

**Comment by amytang0** [comment]
Hi, I would reach out to your account manager for more details about RUX. Generally, every value that gets sent to Plaid helps identify this user as a "returning user", though I am not aware of the specific reasons behind those fields.

Closing this since this isn't specifically a Plaid Link Android SDk request
