### ISSUE TITLE
how to handle onSuccessCallback in Fragment android (Java)

### ISSUE THREAD

**Issue by lahari509** [plaid/plaid-link-android#131]
Hi, 
I am Implementing the plaid integration using Android SDK in Java.
In a fragment class I integrated plaid code. First I am getting the link token from the server and using that token it is able to open the Banks and user able to choose the bank and submitting the credentials. After that the next activity your account has linked successfully is showing. Upto hand Off event is triggered. The next LinkResult handler is not calling in a fragment and I am not able to receive the public token. Can anyone suggest how to handle onActivity Result in Fragment.

  Plaid.create(
                                  mActivity.getApplication(),
                                    new LinkTokenConfiguration.Builder()
                                            .token(getoken)
                                            .logLevel(logLevel)
                                            .build())
                                    .open(mActivity);// this fragment reference activity

` private  LinkResultHandler myPlaidResultHandler = new LinkResultHandler(

            linkSuccess -> {
                String publicToken = linkSuccess.getPublicToken();
                System.out.println("publictoken"+publicToken);
                callaccesstokenapi(publicToken);
                return Unit.INSTANCE;
            },
            linkExit -> {

                LinkError error = linkExit.getError();
                String errorCode = String.valueOf(error.getErrorCode());
                String errorMessage = error.getErrorMessage();
                String displayMessage = error.getDisplayMessage();
                LinkExitMetadata metadata = linkExit.getMetadata();
                String institutionId = metadata.getInstitution().getId();
                String institutionName = metadata.getInstitution().getName();
                String linkSessionId = metadata.getLinkSessionId();
                String requestId = metadata.getRequestId();
                System.out.println("errorMessage"+errorMessage);
                return Unit.INSTANCE;
            }
    );`

  @SuppressLint("LongLogTag")
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == RESULT_OK) {
             if (!myPlaidResultHandler.onActivityResult(requestCode, resultCode, data)) {
                Log.i(TAG, "Not handled");
                if(data != null){
                   System.out.println("dataevent"+data.getExtras().get("data"));
                }
            }
        }
    }

**Comment by JeroenMols** [comment]
How are you opening Link?

You need to ensure to pass the Fragment into `LinkHandler.open()` and not the Activity.

**Comment by lahari509** [comment]
I am opening the link
   Plaid.create(
                                  mActivity.getApplication(),
                                    new LinkTokenConfiguration.Builder()
                                            .token(getoken)
                                            .logLevel(logLevel)
                                            .build())
                                    .open(mActivity);

**Comment by lahari509** [comment]
@JeroenMols I have added the opening link code.

**Comment by zsweigart** [comment]
Hi @lahari509 it might be that your activity is intercepting the call.  See this [stackoverflow post](https://stackoverflow.com/a/6147919) or just try adding 

```
@Override
protected void onActivityResult(int requestCode, int resultCode, @nullable Intent data) {
super.onActivityResult(requestCode, resultCode, data);
}
```
to the activity hosting your fragment

**Comment by JeroenMols** [comment]
Hi @lahari509,

There are two options to open Plaid Link: either from an `Activity` or from a `Fragment`. And I suspect you might be mixing both.

From Activity:

- `Plaid.create( ... ).open(this)`, where `this` refers to your `Activity`
- result will be returned to your `Activity`, so override `onActivityResult()` in your `Activity`

From Fragment:

- `Plaid.create( ... ).open(this)`, where `this` refers to your `Fragment`
- result will be returned to your `Fragment`, so override `onActivityResult()` in your `Fragment`

Imagine if you call `Plaid.create().open(activity)` in your `Fragment` and override the onActivityResult()` in the fragment, then you won't receive a callback. Could that be what was happening?

> Note: Alternatively you can also upgrade to our [latest SDK version 3.2.4](https://github.com/plaid/plaid-link-android/releases/tag/3.2.4) and use the newly added `ActivityResultContract` API.

Please let me know if this works for you.

**Comment by JeroenMols** [comment]
We haven't heard back from you in more than a month, so we're assuming your issue is fixed.

Please feel free to file a new issue (or reopen) should that not be the case.
