### ISSUE TITLE
Bintray Shutting Down May 2021 -- Host artifacts elsewhere?

### ISSUE THREAD

**Issue by JvmName** [plaid/plaid-link-android#134]
Hi! Today JFrog (which owns Bintray/JCenter) announced that they're sunsetting Bintray/JCenter - the last day to access these repositories will be May 2021. jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter

I know a lot of tooling goes into artifact upload to a repository, so I wanted to throw a signal flare up now so nobody is caught by surprise on May 1.

**Comment by amit-affirm** [comment]
Will Plaid artifact be moving off jCenter?

**Comment by amytang0** [comment]
Thanks for the flag yall, we do appreciate it! We discussed this yesterday and will most likely be moving to Maven Central, but will keep you posted. Thanks again!

**Comment by JeroenMols** [comment]
`3.2.4` will be the last release we've release to Bintray/JCenter, we'll be releasing to Maven Central from next month onwards and migrate all artifacts.

**Comment by JeroenMols** [comment]
We've just migrated all our existing artifacts to Maven Central and future releases will also be published there.
https://search.maven.org/artifact/com.plaid.link/sdk-core

Note that we still have one external dependency that's on JCenter, but we are working with them to also migrate. (context: https://github.com/streem/pbandk/issues/120)

**Comment by abhimangalms** [comment]
Which is the alternative for "http://dl.bintray.com/lukaville/maven". Any helps are appreciated. Thanks in advance.
