### ISSUE TITLE
This app is using an old version of the << pbandk-runtime-android >> dependency

### ISSUE THREAD

**Issue by kevingermainbusiness** [plaid/plaid-link-android#140]
Here's the output by Gradle:

    Could not resolve `pro.streem.pbandk:pbandk-runtime-android:0.10.0-beta.2.`
    Required by:
         project :app > com.plaid.link:sdk-core:3.2.5

This beta version is no longer accessible from jCenter() or mavenCentral(), you guys should update this library with the new working stable version **v0.9.1**  found here `https://github.com/streem/pbandk`

**Comment by JeroenMols** [comment]
Thanks for reporting this @kevingermainbusiness.

The dependency in question `0.10.0-beta.2` only has a release variant published to `jCenter()` and Gradle`s variant-aware dependency resolution isn't able to resolve a variant that matches the `debug` build type. (Note: this is already solved in the next `pbandk` release).

Can you try adding the following to your `build.gradle` file?

```groovy
android {
    ...
    
    buildTypes {
        debug {
            matchingFallbacks += "release"
        }
    }
}
```

I'll get back to you when I have an ETA of a fix in our SDK.

**Comment by JeroenMols** [comment]
duplicate of https://github.com/plaid/plaid-link-android/issues/139

**Comment by kevingermainbusiness** [comment]
I did add it to Gradle, this issue is now gone 👍 Thanks

**Comment by JeroenMols** [comment]
FYI: We've put out a new SDK release `3.2.6` with a fix.
You can upgrade to that version and remove the workaround.
