### ISSUE TITLE
JavaNetConnectException when pressing on Open Link button in MainActivity

### ISSUE THREAD

**Issue by kevingermainbusiness** [plaid/plaid-link-android#142]
`java.net.ConnectException: failed to connect to /10.0.2.2 (port 8000) from /10.0.2.16 (port 38158) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)`

Attribute usesCleartextTraffic is only used starting from API level 23 and I'm using an API level 29 emulator, so it should work just fine.
Can the team please provide us with clear ways to make the localhost work with this testing demo, thanks in advance

**Comment by amytang0** [comment]
Double-checking, does your URL use https instead of http?

**Comment by kevingermainbusiness** [comment]
It uses http, it compiles fine, but once the button click is done, it crashes.

It uses the exact same code as provided by this repo, here's the code for the base url address in this repo :
```
// This value is setup to work with emulators. Modify this value to your PC's IP address if not.
  private const val baseUrl = "http://10.0.2.2:8000"
```
[here](https://github.com/plaid/plaid-link-android/blob/master/app/src/main/java/com/plaid/linksample/network/LinkTokenRequester.kt)

**Comment by amytang0** [comment]
Perfect, and have you run the `start_server.sh` script with your `client_id` and `secret_sandbox`?

**Comment by amytang0** [comment]
If you open `Terminal`, then `cd` into the folder where you've downloaded the sample app code, you should be able to type `sh start_server.sh <client_id> <sandbox_secret>` to start the local server

**Comment by kevingermainbusiness** [comment]
I went to the directory, typed this command like so, with the appropriate client_id and sandbox_secret:
 **sh start_server.sh client_id  sandbox_secret**

The output by the terminal is :

sh: start_server.sh: No such file or directory

Then I typed it like so: sh start_server.sh <client_id> <sandbox_secret>

The output by the terminal is:

zsh: parse error near `<'

**Comment by amytang0** [comment]
It sounds like you may not be in the correct directory (e.g. `~/Downloads/plaid-link-android`). Your `ls` should show something like
```
$ ls
LICENSE                docs                   local.properties
README.md              gradle                 plaid-link-android.iml
app                    gradle.properties      server
build                  gradlew                settings.gradle
build.gradle           gradlew.bat            start_server.sh
```
You basically want to run the `start_server.sh` script. You can also see directions in the README

**Comment by kevingermainbusiness** [comment]
It works! Thank you so much for your help and time! I made a mistake that made the **start_server.sh** file go missing. I fixed it ,rerun the script in the Terminal without the <> for the client_id and sandbox_secret credentials, and now the app  runs fine and no longer crashes 👍

**Comment by amytang0** [comment]
Perfect, glad that worked 😄 

Thank you for calling this issue out, the team will try to record a video/make these instructions clearer.
