### ISSUE TITLE
Expose dismissPlaidLink API to close Link UI 

### ISSUE THREAD

**Issue by alparp27** [plaid/plaid-link-android#152]
# The problem
My client would like to dismiss Link UI when user selects a bank when user subscription does not match a criteria.  So I would like plaid UI when SELECT_INSTITUTION event occurs from my controller.

# Environment

All

# Steps to Reproduce

plaid handler does not have APIs to dismiss UI, although user does have cross button on top right to dismiss UI at anytime but I cannot achieve same using APIs.  Is it possible to expose the same or let me know if there is a way to do this.

For example:

**Comment by amytang0** [comment]
Hi, we have previously seen abusive usage of this API and thus have not exposed it on Android. Thank you and sorry for the inconvenience!
