### ISSUE TITLE
Plaid uses generic string names

### ISSUE THREAD

**Issue by dan-0** [plaid/plaid-link-android#153]
# The problem

After implementing the SDK we found lint failures due to Plaid using both the `search` and `app_name` strings in the SDK (I imagine there are more than both of these). The fix on our side was simple for this, we renamed the string names, but as a library, Plaid should be using more specific string naming conventions. (ie. a `plaid_sdk_[name]` convention) to avoid conflicts, even if those implementations are private they can still cause unexpected behavior from applications using the SDK.

# Environment

Using Plaid sdk-core v3.2.6 on any modern version of Android with Android Studio.

# Steps to Reproduce

1. In any application import Plaid sdk-core v3.2.6
2. Add a string for `app_name` or `search` to `strings.xml` and give it a unique string value
3. Use the string in a XML view layout
4. Launch app and note the application supplied unique string value
5. Delete the app implementation of `app_name` or `search`
6. Reload the app
7. Note that the application now uses Plaid's string (ie. if you used `app_name` and deleted it, anything using `app_name` is now "Link"

# Expected Result
If `app_name` or `search` names in strings.xml are deleted or renamed, anything referencing them should fail.

# Screenshots
N/A

# Logs
N/A

# Code To Reproduce Issue
See steps to reproduce

**Comment by amytang0** [comment]
Hey thanks for flagging this! We had an effort to add the "plaid" prefix to our resource names around 2.x but clearly missed a few. We'll do another sweep before next release.

**Comment by amytang0** [comment]
Hi, our newest release 3.3.0 should mitigate both of those issues. Thank you!
