### ISSUE TITLE
plaid_sentry_api_key

### ISSUE THREAD

**Issue by RyanNewsom** [plaid/plaid-link-android#162]
Hello,

This key/value is coming from your sdk in a values.xml file when I consume it from my Android application. I have not posted the value for security reasons. I am curious why you are using sentry, and was unable to find any explanation in your sdk documentation. I don't think I've ever seen a third party sdk use a crash reporting tool internally like this. Can you please provide an explanation? 

Thanks.

**Comment by zsweigart** [comment]
Hi @RyanNewsom 
We use Sentry so we can monitor if our SDK is crashing your app so we can proactively disable and internal features that may have caused the issue. The alternative would be to have no crash reporting in our SDK and rely on developer reports which is a slow feedback loop.

**Comment by JeroenMols** [comment]
Hopefully Zach's explanation alleviates the concerns you have/had.
As I didn't see any follow up questions, I'm going to close this issue.

Please don't hesitate to reach out should you have more questions or concerns!
