### ISSUE TITLE
Plaid versions > 3.2.4 crash when launched from an Android plugin

### ISSUE THREAD

**Issue by TheBetterJustinTang** [plaid/plaid-link-android#163]
# The problem
Launching Plaid with plaidHandeler.open() is resulting in an app crash for versions greater than 3.2.4 when run in an android plugin embedded in flutter with flutter run. I have a suspicion this has to do with how transitive decencies are being resolved in Plaid specifically with _Lpbandk and google/protobuf_. 

*Note when tested with v3.2.6 the app Plaid launches but gets stuck infinitely loading.

# Environment
|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | API S              |
| Android Devices/Emulators    | Pixel 4 emulator API S              |

# Steps to Reproduce
1) Within an android flutter plugin run the application with flutter run
2) Launch Plaid Link with PlaidHandler.open and a valid linkToken configuration.

# Expected Result
We expect plaid to launch without crashing on SDK versions > 3.2.4

# Screenshots
| 3.2.4 | 3.3.1 |
| -------- | ------- |
| [Working Launch mov](https://user-images.githubusercontent.com/77077870/118849497-ccc87e80-b89d-11eb-9ef3-d3b5746e5605.mov) | [Crash on higher SDKs mov](https://user-images.githubusercontent.com/77077870/118849515-d0f49c00-b89d-11eb-906e-587670aa3ae9.mov) | 

# Logs
![Crash log](https://user-images.githubusercontent.com/77077870/118866780-5719de00-b8b0-11eb-8d36-242f58b4e1e9.png)
` java.lang.NoClassDefFoundError: Failed resolution of: Lpbandk/Message;
E/AndroidRuntime(27878):        at com.plaid.internal.t.requestBodyConverter(SourceFile:2)
E/AndroidRuntime(27878):        at retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:315)
E/AndroidRuntime(27878):        at retrofit2.Retrofit.requestBodyConverter(Retrofit.java:293)
E/AndroidRuntime(27878):        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:778)
E/AndroidRuntime(27878):        at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:325)
E/AndroidRuntime(27878):        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:206)
E/AndroidRuntime(27878):        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
E/AndroidRuntime(27878):        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
E/AndroidRuntime(27878):        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
E/AndroidRuntime(27878):        at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
E/AndroidRuntime(27878):        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
E/AndroidRuntime(27878):        at $Proxy3.a(Unknown Source)
E/AndroidRuntime(27878):        at com.plaid.internal.n.a(SourceFile:48)
E/AndroidRuntime(27878):        at com.plaid.internal.po0.a(SourceFile:28)
E/AndroidRuntime(27878):        at com.plaid.internal.po0$b.invokeSuspend(Unknown Source:12)
E/AndroidRuntime(27878):        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(27878):        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(27878):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(27878):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(27878):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(27878):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(27878):        at android.app.ActivityThread.main(ActivityThread.java:7695)
E/AndroidRuntime(27878):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27878):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(27878):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
E/AndroidRuntime(27878): Caused by: java.lang.ClassNotFoundException: Didn't find class "pbandk.Message" on path: DexPathList[......]`

When the app is built and run in android we get this error message:
![Android run build error](https://user-images.githubusercontent.com/77077870/118874078-7d437c00-b8b8-11eb-892e-7db7bf146704.png)
Which is resolved with a ` packagingOptions { pickFirst 'google/protobuf/*' }`. Once added Plaid 3.3.1 still crashes in flutter but works in android.

# Code To Reproduce Issue
**Codes snippet (Works in 3.2.4 but not in any version higher) :**
```kotlin       
private fun launchPlaid(linkToken: String) {
        val linkTokenConfiguration = linkTokenConfiguration {
            token = linkToken
        }
        activity?.let {
            val plaidHandler: PlaidHandler = Plaid.create(it.application, linkTokenConfiguration)
            plaidHandler.open(it)
        }  ?: pendingResult.error("Launch Plaid error", "Activity was null", null)
    }

**Comment by amytang0** [comment]
Hey Justin,

Thanks for the report, would you mind sharing your Gradle dependencies file to help repro? 

Cheers,
Amy

**Comment by TheBetterJustinTang** [comment]
Hey Amy!

Here is the gradle file for the plugin.
```
group 'com.betterment.plaid'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.3.72'
    repositories {
        google()
        mavenCentral() // Include to import Plaid Link Android SDK
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 23
    }
    lintOptions {
        disable 'InvalidPackage'
    }

    // Enable Java 8 support for Link to work
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.plaid.link:sdk-core:3.2.4"
}

**Comment by amytang0** [comment]
Any chance you can grab the output from `./gradlew :app:dependencies` when you're pulling the `3.3.1` dependency? Still having difficulty repro-ing

**Comment by TheBetterJustinTang** [comment]
@amytang0 yup! Here the txt file: 
[dependencies.txt](https://github.com/plaid/plaid-link-android/files/6516769/dependencies.txt)

Just a heads up repoing is complex! Since Plaid only fails while inside an android plugin embedded in our flutter app.

**Comment by JeroenMols** [comment]
Interestingly, our Plaid SDK isn't present in the output of the `dependencies.txt` file.
Is `app` the name of the module holding the flutter plugin?

**Comment by TheBetterJustinTang** [comment]
> Interestingly, our Plaid SDK isn't present in the output of the `dependencies.txt` file.
> Is `app` the name of the module holding the flutter plugin?

Sorry the plaid module is named `plaid` heres the file for Plaid : 
[plaidDependencies.txt](https://github.com/plaid/plaid-link-android/files/6592838/plaidDependencies.txt)

**Comment by JeroenMols** [comment]
@TheBetterJustinTang Since this only happens when you are using our SDK in a flutter plugin, I'm thinking this may have to do with how Flutter uses Gradle to create plugins.

Two thoughts pop to mind:
1. **PackagingOptions is not supported for Flutter plugins.** Can you try using SDK version `3.3.0` instead? This doesn't require the packagingOptions workaround (`packagingOptions { pickFirst 'google/protobuf/*' }`). 
1. **Transitive dependencies aren't working** Can you try adding a dependency on `pbandk` explicitly? In your Flutter plugin, add the following:

```groovy
dependencies {
    ...
    implementation "com.plaid.link:sdk-core:3.3.0"
    implementation "pro.streem.pbandk:pbandk-runtime:0.10.0-beta.4"
}
```

Thank you!

**Comment by TheBetterJustinTang** [comment]
@JeroenMols 
Neither of those options seemed to work, I'm still getting a crash with the same message.   
` implementation "pro.streem.pbandk:pbandk-runtime:0.10.0-beta.4"`

**Comment by TheBetterJustinTang** [comment]
@JeroenMols updating to version 3.4.0 worked! Thanks!
