### ISSUE TITLE
Login Screen not scrollable in Android

### ISSUE THREAD

**Issue by ar-abdulazeez** [plaid/plaid-link-android#167]
# The problem

On the login screen, the view is now scrollable. When the keyboard is up, there is no way to go to the password field by scrolling. One can use the next button in the keyboard but not all Android users are familiar with that.

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | 21                |
| Android Devices/Emulators    | Pixel XL physical                |
    implementation 'com.plaid.link:sdk-core:3.2.1'

# Steps to Reproduce

Open the Plaid login screen in and Android emulator or device

# Expected Result
The view should be scrollable.

# Screenshots

![Plaid](https://user-images.githubusercontent.com/59614775/118980498-87f92200-b947-11eb-9c46-908ceba4e19b.gif)

# Logs
None

# Code To Reproduce Issue
Any Android app - basic. No special code to repro this issue.

**Comment by amytang0** [comment]
Hi, thanks for the flag!
We already have a fix for this issue and that will go out in next release (3.3.2)

**Comment by JeroenMols** [comment]
We've just release a fix, please upgrade to `3.4.0`.
