### ISSUE TITLE
Crash in prod

### ISSUE THREAD

**Issue by alparp27** [plaid/plaid-link-android#168]
# The problem

Crash in live app

# Environment
| Android OS Version                    | e.g. 7.0.             |
| Android Devices/Emulators    | e.g. ZTE               |

# Steps to Reproduce
Unknown

Stack trace from firebase:
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.everlance/com.plaid.internal.link.LinkWebViewActivity}: kotlin.UninitializedPropertyAccessException: lateinit property INSTANCE has not been initialized
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2697)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
Caused by kotlin.UninitializedPropertyAccessException
lateinit property INSTANCE has not been initialized
com.plaid.link.internal.BasePlaid$Companion.getINSTANCE (SourceFile:1)
com.plaid.internal.jg0.a (SourceFile:46)
com.plaid.internal.ve0.onActivityCreated (SourceFile:5)
androidx.fragment.app.Fragment.performActivityCreated (Fragment.java:2718)
androidx.fragment.app.FragmentActivity.onStart (FragmentActivity.java:541)
com.plaid.internal.xe0.onStart (SourceFile:1)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1252)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)

**Comment by JeroenMols** [comment]
Hi @alparp27 ,

Thanks for reporting this issue.

What version of our SDK are you on? This should be completely fixed in `3.3.1` as we've made an architectural change to solve this once and for all.

Please let me know if upgrading works for you.

Warm regards,
Jeroen

**Comment by alparp27** [comment]
I was 3.2.0, I will upgrade and monitor.

**Comment by JeroenMols** [comment]
@alparp27 Have you been able to conclude anything from your monitoring?
If you've no longer seen this, we'd like to move ahead and close this issue.

**Comment by alparp27** [comment]
I have not seen it, I will let you know if I do.

**Comment by JeroenMols** [comment]
Thanks for letting me know!

Given that we haven't gotten any new reports about this and that the architectural change should have structurally addressed this, I suggest we close the ticket for now. Please don't hesitate to reopen or file a new issue should you see this issue again.
