### ISSUE TITLE
Transitive okhttp dependency

### ISSUE THREAD

**Issue by shaurya947** [plaid/plaid-link-android#17]
Currently in our project we use okhttp v3.12.0.

I noticed that adding the plaid SDK (v0.3.0) started throwing a few errors for deprecated functions in okhttp because the plaid SDK is pulling in okhttp v4.2.2 into the project.

I tried:

```
implementation('com.plaid.link:sdk-core:0.3.0') {
        exclude module: 'okhttp'
    }
```

as well as

```
implementation('com.plaid.link:sdk-core:0.3.0') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
```

without any luck. How can I successfully avoid pulling in the transitive okhttp dependency?

**Comment by shaurya947** [comment]
I ran the gradle dependencies task and was able to figure out that the actual dependency being pulled in is the `logging-interceptor`. So I changed my exclude to:

```
implementation('com.plaid.link:sdk-core:0.3.0') {
        exclude group: 'com.squareup.okhttp3', module: 'logging-interceptor'
    }
```

This removed the errors for the deprecated functions and let me build and run the app. However, the app just crashes at start-up with the following message:

```
java.lang.NoSuchMethodError: No direct method <init>(Lokhttp3/logging/HttpLoggingInterceptor$Logger;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/logging/HttpLoggingInterceptor; or its super classes (declaration of 'okhttp3.logging.HttpLoggingInterceptor' appears in /data/app/com.cover.android-P_ZsT2Rl7hGs3ZVgzZKMGg==/base.apk:classes4.dex)
        at com.plaid.networking.PlaidRetrofit.createRetrofitInstance(PlaidRetrofit.kt:64)
        at com.plaid.networking.PlaidRetrofit.getRetrofit(PlaidRetrofit.kt:60)
        at com.plaid.crashreporting.sentry.SentryCrashApi.init(SentryCrashApi.kt:43)
        at com.plaid.link.Plaid$Companion.create(Plaid.kt:74)
        at com.cover.android.CoverApplication.setupPlaidSDK(CoverApplication.kt:208)
        at com.cover.android.CoverApplication.onCreate(CoverApplication.kt:124)
...
```

Looks like Plaid.create() can't find a method in the okhttp library that it needs to initialize..? I'll try adding an explicit dependency on the `loggin-interceptor` v3.12.0 to see if it resolves this error.

**Comment by vladir95** [comment]
We have the same issue in our app too

**Comment by amytang0** [comment]
Hello, thank you for bringing this to our attention. We will get a fix out soon in our next release, but in the meantime using IntelliJ/Android Studio's Code Cleanup can help you get upgraded to 4.0 fast. https://square.github.io/okhttp/upgrading_to_okhttp_4/

**Comment by amytang0** [comment]
Please upgrade to 0.3.3, thank you!
