### ISSUE TITLE
Enabling Update Mode on 3.3.1

### ISSUE THREAD

**Issue by tonytonytoan** [plaid/plaid-link-android#170]
# The problem

I'm migrating Plaid from 2.x to 3.x. When creating the Link to start the Plaid Link flow, I'm using the `LinkTokenConfiguration.Builder`. To enable update mode, previously we would set the `publicToken` field. In 3.x, I add to `extraParams` the value `{"access_token": "PUBLIC_KEY"}`. This doesn't take the user straight to credentials screen. 

However, if user selects correct FI, credentials, and external account, the external account is relinked.

How do we build the Plaid Link to enable update mode in 3.x?

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | API 30               |
| Android Devices/Emulators    | e.g. Pixel 4XL emulator            |
| Development environment | sandbox | 

# Expected Result
Relink flow where user is taken straight to the credentials screen.

# Code To Reproduce Issue
```
    val tokenConfigurationBuilder = LinkTokenConfiguration.Builder()
      .token(linkToken)
      .logLevel(if (BuildConfig.DEBUG) LinkLogLevel.VERBOSE else LinkLogLevel.ERROR)
    if (key != null) {
      tokenConfigurationBuilder.extraParams(mapOf(Pair("access_token", key)))
    }

    val tokenConfiguration = tokenConfigurationBuilder.build()
    Plaid.create(
      application,
      tokenConfiguration
    ).open(fragment)
```

**Comment by JeroenMols** [comment]
Hi @tonytonytoan,

I see that you are using link tokens. To use update mode, you can use the old `access_token` to create a new link token, which you can use in the `TokenConfiguration.Builder` as the token to open Link.

More information here: https://plaid.com/docs/link/update-mode/#using-update-mode

**Comment by tonytonytoan** [comment]
Hi @JeroenMols!

Please assist me as I'm not sure I understand here. `LinkTokenConfiguration.Builder` no longer provides a setter for the `access_token`. If I pass

```
    val tokenConfigurationBuilder = LinkTokenConfiguration.Builder()
      .token(accessToken)
```

Plaid Link fails to load and `Invalid clientName` and `Invalid product` is thrown.

Adding the `access_token` as a k-v to `extraParams` also doesn't work. Is the key supposed to be `access_token`?

Thanks!

**Comment by JeroenMols** [comment]
You cannot pass an `access_token` into Link, not in the `LinkTokenConfiguration.Builder`, nor via `extraParams`.

Instead, first exchange the `access_token` for a new link token:

```
curl -X POST https://sandbox.plaid.com/link/token/create \
-H 'Content-Type: application/json' \
-d '{
  "client_id": "CLIENT_ID",
  "secret": "SECRET",
  "client_name": "My App",
  "user": { "client_user_id": "UNIQUE_USER_ID" },
  "country_codes": ["US"],
  "language": "en",
  "webhook": "https://webhook.sample.com",
  "access_token": "ENTER_YOUR_ACCESS_TOKEN_HERE"
}'
```

Then use the returned token in the `LinkTokenConfiguration.Builder`:

```kotlin
val tokenConfigurationBuilder = LinkTokenConfiguration.Builder().token(linkToken)
```

More explanation and code examples here: https://plaid.com/docs/link/update-mode/#using-update-mode

**Comment by JeroenMols** [comment]
Hi @tonytonytoan,

Any chance you've been able to try out my suggestion above?

Thanks!

**Comment by tonytonytoan** [comment]
Hi @JeroenMols,

Thanks for the clarification, appreciate the help and I'll have a look in the next 24 hours.

**Comment by JeroenMols** [comment]
@tonytonytoan have you been able to take a look?
