### ISSUE TITLE
oAuth Update Mode

### ISSUE THREAD

**Issue by roarapps** [plaid/plaid-link-android#186]
Hello,

In the Plaid docs, when we are in Update Link mode for Android. Your docs seem to say that we do not need to pass in the package name like we have to in Create.

However, in our own testing this doesn't seem to be true. If we don't pass in the package name then the link out to oAuth banks do not work.

https://plaid.com/docs/link/oauth/

**Comment by amytang0** [comment]
Hi, thanks for flagging that part of our docs! You will indeed need to pass the `android_package_name` (and `redirect_uri` on iOS) even during update mode. Unfortunately, I can't seem to find the part of our docs that you're referring to, would you mind sharing the exact section?

**Comment by roarapps** [comment]
Hello,

It might just be me but i find it confusing to read because under the "Client-side configuration"  there is a table and iOS has additional link configuration required so it was easy to see its needed.

It says NO under android so i misunderstood.

**Comment by amytang0** [comment]
Ah, thank you! That is indeed confusing, we'll update that
