### ISSUE TITLE
Plaid SDK 3.5.0 update error (Duplicate class org.bouncycastle.LICENSE)

### ISSUE THREAD

**Issue by RajaReddyP** [plaid/plaid-link-android#187]
In my application, we are using OKTA SDK (it has a dependency on the bouncy-castle) along with Plaid, If I try to update plaid SDK to the latest 3.5.0 we are facing issues like below.

**Error:**Duplicate class org.bouncycastle.LICENSE found in modules jetified-bcprov-jdk14-1.69 (org.bouncycastle:bcprov-jdk14:1.69) and jetified-bcprov-jdk15on-1.64 (org.bouncycastle:bcprov-jdk15on:1.64)

Currently, we are using: Plaid SDK-3.2.2
OKTA auth SDK-2.0.0

**Comment by zsweigart** [comment]
The Plaid sdk is compatible with bouncy castle 1.64 so you  could do something like

```
    implementation ("com.plaid.link:sdk-core:3.5.0") {
        exclude group: 'org.bouncycastle'
    }
    implementation 'com.okta.authn.sdk:okta-authn-sdk-api:2.0.0'
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:2.0.0') {
        exclude group: 'com.okta.sdk', module: 'okta-sdk-httpclient'
    }
    implementation 'com.okta.sdk:okta-sdk-okhttp:2.0.0'
```

However, it's generally better to use newer versions of security libraries so I tested the compilation of 

```
    implementation "com.plaid.link:sdk-core:3.5.0"
    implementation ('com.okta.authn.sdk:okta-authn-sdk-api:2.0.0') {
        exclude group: 'org.bouncycastle'
    }
    implementation('com.okta.authn.sdk:okta-authn-sdk-impl:2.0.0') {
        exclude group: 'com.okta.sdk', module: 'okta-sdk-httpclient'
        exclude group: 'org.bouncycastle'
    }
    implementation ('com.okta.sdk:okta-sdk-okhttp:2.0.0') {

        exclude group: 'org.bouncycastle'
    }
```

And the Link sdk works as expected but I did not test the Okta integration so I would recommend reaching out to their team.

**Comment by MMorg76114** [comment]
@zsweigart is there a way to determine which versions of bouncy castle the plaid SDK is compatible with? 

In my case I am dealing with a project that needs to build **_Plaid SDK 3.5.0+_** and _**Stripe SDK 16.1.1+**_ 

**_org.bouncycastle:bcpkix-jdk14:1.69_**: Plaid

vs
**_org.bouncycastle:bcprov-jdk15to18:1.67_**: Stripe

**Comment by jt-gilkeson** [comment]
Plaid 3.5.1 and Stripe 17.1.2 seem to conflict, this is what I did to deal with it.  Is this the suggested approach?  

    implementation 'com.plaid.link:sdk-core:3.5.1'
    implementation('com.stripe:stripe-android:17.1.2'){
        exclude group: 'org.bouncycastle'
    }

**Comment by jt-gilkeson** [comment]
Plaid 3.5.1 and Stripe 17.1.2 seem to conflict, is this the suggested apprproach?

    implementation('com.plaid.link:sdk-core:3.5.1') {
        exclude group: 'org.bouncycastle'
    }
    implementation 'com.stripe:stripe-android:17.1.2'

**Comment by maxim-logunov** [comment]
Same problem for me when using Plaid 3.5.1 and and Stripe 17.2.0. Suggested approach seems to work:
`implementation('com.plaid.link:sdk-core:3.5.1') {
        exclude group: "org.bouncycastle"
  }
  implementation 'com.stripe:stripe-android:17.2.0'
  `

**Comment by JeroenMols** [comment]
test@jt-gilkeson We don't recommend excluding `org.bouncycastle` as a transitive dependency from the Plaid SDK. This is because that would cause the Plaid SDK to use the transitive dependency version of `org.bouncycastle` specified by Stripe (which in this case is older and could have security issues).

Instead we recommend replacing the `Java 1.4` artifact of `org.bouncycastle` requested by the Plaid SDK with the `Java 1.5 to 1.8` artifact to be in line with the variant that Stripe requests. This will leave it up to Gradle to decide on what `org.bouncycastle` version to use, which will end up being the highest specified version.

You can do so by adding the following to your `build.gradle` file:

```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute module("org.bouncycastle:bcpkix-jdk14:1.69") using module("org.bouncycastle:bcpkix-jdk15to18:1.69")
    }
}
```

We'll review internally at what flavor of `org.bouncycastle` (JDK support) we should use moving forward.

**Comment by JeroenMols** [comment]
FYI in SDK `3.6.1` and onwards we changed the Plaid SDK `org.bouncycastle` transitive dependency to the one supporting Java `1.5` to `1.8`.

So please update to our latest SDK `3.6.2` and remove the workaround above.
