### ISSUE TITLE
Plaid Link SDK freezes(incorrect routing number flow) - microdeposit flow

### ISSUE THREAD

**Issue by iamjosephmj** [plaid/plaid-link-android#194]
# The problem

User cannot proceed while after changing the incorrect routing number. Plaid-link SDK

# Environment

Android OS Version : 9, 10, 11              
Android Devices/Emulators: All devices and  emulators        

Plaid SDK: 3.6.0

# Steps to Reproduce

- Follow microdeposit flow.
- Give routing number as : 011401533
- give account number as : 1111222233330000

This will result in error at the end(expected).

- now go back and change the routing number to
110000000
- account number: 1111222233330000

# Expected Result

User should be able to complete the flow.

# Screenshots

Please refer to the video : https://user-images.githubusercontent.com/18631114/134048412-ba86e704-b616-4c8a-9f72-0cec1fae44ee.mp4

**Comment by amytang0** [comment]
Thanks for flagging this! Would it be possible for you to share your `client_id` to help track down the related logs? Thank you!

**Comment by iamjosephmj** [comment]
@amytang0 you can see the client_id in here-> https://dashboard.plaid.com/support/case/341632. Please contact your support team.

**Comment by amytang0** [comment]
Perfect, thanks!

**Comment by iamjosephmj** [comment]
@amytang0 as user is not able to go back like the old webview flow.. The issue seems to be resolved. 

Keep up the good work @amytang0 👍

closing this ticket.
