### ISSUE TITLE
Didn't get callback when click on cancel of chrome tab in V0.3.2 [Production]

### ISSUE THREAD

**Issue by hitesh-banknovo** [plaid/plaid-link-android#20]
![plaid_callback_issue](https://user-images.githubusercontent.com/51733544/72595499-f3844700-392f-11ea-9d4d-58a9e365ac11.png)

When Plaid SDK chrome tab cancel (left-top) button tapped, it will redirect to LinkActivity (Not sure) that shows loading view only as attached in the screenshot. But not get the callback in **`onActivityResult`** method of calling activity.

**Comment by zsweigart** [comment]
Hi @hitesh-banknovo this should be fixed in the latest release.

However, have you signed up for a developer account on https://dashboard.plaid.com/ if not where did you get your keys?  Was this in sandbox, development or prod?

**Comment by hitesh-banknovo** [comment]
Hi @zsweigart 
We have a company account and It is a prod issue. 
I checked in V.0.3.2 and the issue is there so could you please tell me which version it is resolved?

**Comment by zsweigart** [comment]
This issue should be solved in 0.3.3; however, the chrome custom tabs was not intended to be rolled out for 0.3.2. We have checked and turned it off so you should be seeing the default webview implementation again.

**Comment by hitesh-banknovo** [comment]
Thank you, will test it.

**Comment by hitesh-banknovo** [comment]
It is fixed in version 0.3.4.

But there is another issue while reconnecting plaid account with the public token is **`com.plaid.linkbase.models.PlaidLinkConfigurationInvalidTokenException`** and error message is **The public token provided is not formatted correctly.** though the public token is correct.

**Comment by hitesh-banknovo** [comment]
Creating a new issue for new
