### ISSUE TITLE
Fatal Crash on launching Sample App with Plaid 3.7.0

### ISSUE THREAD

**Issue by GangChenGoCode** [plaid/plaid-link-android#213]
# The problem

Plaid-Link-Android 3.7.0

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | 31 & 32             |
| ABI                      |  x86_64
| Android Devices/Emulators    | Pixel 2 emulator              |

# Steps to Reproduce

install app-debug.apk on both emulators 31 & 32 and launch the sample app

# Expected Result
successful launching

# Screenshots
crashed immediately no screenshot available

# Logs
17081-17108/com.plaid.linksample E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.plaid.linksample, PID: 17081
    java.lang.IllegalArgumentException: com.plaid.linksample: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:196)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:128)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:93)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

# Code To Reproduce Issue
original sample code

**Comment by amytang0** [comment]
Hi, just want to confirm, are you targeting Android SDK 30+?

**Comment by GangChenGoCode** [comment]
> Hi, just want to confirm, are you targeting Android SDK 31+?
yes, as what comes in the sample app

    compileSdkVersion 31
    defaultConfig {
        applicationId "com.plaid.linksample"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 1
        versionName "1.0"
    }

**Comment by amytang0** [comment]
Hey, we managed to repro this and will have a permanent fix in our next release, but in the meantime, we have a bandaid fix. The offending piece of code is the [`workmanager` dependency](https://developer.android.com/jetpack/androidx/releases/work#2.7.0-alpha02), so this issue is fixed if you force it to a version that doesn't have issues with 31+, e.g.
```
implementation("androidx.work:work-rxjava2:2.7.1") {
    force true
}

implementation("androidx.work:work-runtime-ktx:2.7.1") {
  force true
}
```

**Comment by GangChenGoCode** [comment]
> Hey, we managed to repro this and will have a permanent fix in our next release, but in the meantime, we have a bandaid fix. The offending piece of code is the [`workmanager` dependency](https://developer.android.com/jetpack/androidx/releases/work#2.7.0-alpha02), so this issue is fixed if you force it to a version that doesn't have issues with 31+, e.g.
> 
> ```
> implementation("androidx.work:work-rxjava2:2.7.1") {
>     force true
> }
> 
> implementation("androidx.work:work-runtime-ktx:2.7.1") {
>   force true
> }
> ```

Thanks, this solutions works, thanks
