### ISSUE TITLE
Lint error: TrustAllX509TrustManager from bouncy castle

### ISSUE THREAD

**Issue by horf31** [plaid/plaid-link-android#218]
# The problem

I'm trying to update the plaid SDK from 2.0.0 to 3.7.0.

One of the lint errors I got was: `android/app/org/**bouncycastle**/est/jcajce/JcaJceUtils$1.class: Error: checkClientTrusted is empty, which could cause insecure network traffic due to trusting arbitrary TLS/SSL certificates presented by peers [TrustAllX509TrustManager]`

`Explanation for issues of type "TrustAllX509TrustManager":
   This check looks for X509TrustManager implementations whose
   checkServerTrusted or checkClientTrusted methods do nothing (thus trusting
   any certificate chain) which could result in insecure network traffic
   caused by trusting arbitrary TLS/SSL certificates presented by peers.`

bouncycastle was being depended on by Plaid.

What's the best way to go about this?

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | 11    |
| Android Devices/Emulators    | Nexus 5X emulator        |

I think the bouncy castle version is `org.bouncycastle:bcpkix-jdk15to18:1.69` looking at the dependency tree.

+--- org.bouncycastle:bcpkix-jdk15to18:1.69
|    |    |    |    +--- org.bouncycastle:bcprov-jdk15to18:1.69
|    |    |    |    \--- org.bouncycastle:bcutil-jdk15to18:1.69
|    |    |    |         \--- org.bouncycastle:bcprov-jdk15to18:1.69

# Steps to Reproduce

`./gradlew :app:lintProdDebug`

**Comment by amytang0** [comment]
Hi, some of our partner financial institutions require this method TLS/SSL so while we discourage its use generally, we unfortunately must keep it as part of the dependency tree. Thank you!
