### ISSUE TITLE
Blank page issue in Android version 8

### ISSUE THREAD

**Issue by prabavgts** [plaid/plaid-link-android#224]
See the below screen record, it shows a blank page after signing in. Sometimes it shows up while in landscape mode.  I only face this problem in Android version 8.

https://user-images.githubusercontent.com/67138992/161030984-b78ca93e-d701-41ce-b809-604a334c7505.mp4

**Comment by phoenixy1** [comment]
Closing this issue as it is over 2.5 years old, we have not been able to reproduce, no other customers have reported it, and it only occurs on a version of Android that has been EOL'ed. If this happens on newer versions of the SDK with currently supported Android versions, please feel free to re-open.
