### ISSUE TITLE
Plaid sdk is showing only loading screen on devices running Android 7.0 (API Level 24)

### ISSUE THREAD

**Issue by antonPolosin** [plaid/plaid-link-android#225]
# The problem
As stated in the title

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | Android 7.0 (API Level 24)                |
| Android Devices/Emulators    | Pixel 2 emulator                |

# Steps to Reproduce
Open Plaid sdk on device running Android 7.0 (API Level 24) 

# Expected Result
Plaid should show greeting screen

# Screenshots
<img width="386" alt="Screen Shot 2022-05-16 at 11 35 11 am" src="https://user-images.githubusercontent.com/18572353/168505730-a8593f77-6a75-41b0-b00c-da8cbc594399.png">

# Logs
Not sure if it's helpful but that what i can see in logcat
`W/art: Attempt to remove non-JNI local reference, dumping thread`
this line is repeted

**Comment by amytang0** [comment]
What version of the SDK are you using?

**Comment by antonPolosin** [comment]
3.6.0

**Comment by antonPolosin** [comment]
Bumped Plaid sdk version to 3.7.0 but it's still showing only loading screen on api level 24

**Comment by amytang0** [comment]
Can you post a `link-session-id` of a failing session? And/or make sure your caches are cleared and pulling in the new dependency?

**Comment by GuyDavisGF** [comment]
I'm seeing this same issue still on sdk version `3.9.0` 
Same Android API level 24. Same log message repeated.

**Comment by brianwernick** [comment]
We are seeing this as well with sdk version `3.10.0`

###### Logcat
```
W/art: Attempt to remove non-JNI local reference, dumping thread
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12954
D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
I/chromium: [INFO:CONSOLE(7)] "The key "viewport-fit" is not recognized and ignored.", source: https://secure.plaid.com/link/v2/stable/link.html?androidSdkImplementation=inProcess&env=sandbox&isMobile=true&isWebview=true&linkOpenId=e740c530-213d-410b-9ccd-2a1035b8cec0&linkPersistentId=a3801031-39d3-4b01-82be-e17956331e5e&linkSdkVersion=3.10.0&token=link-sandbox-e4de7ba0-cd8e-4038-a581-07cd00970ec9 (7)
W/art: Attempt to remove non-JNI local reference, dumping thread
I/chromium: [INFO:CONSOLE(2)] "TypeError: j.replaceWith is not a function", source: https://secure.plaid.com/link/2.0.1340/flink.js (2)
I/chromium: [INFO:CONSOLE(2)] "Uncaught TypeError: j.replaceWith is not a function", source: https://secure.plaid.com/link/2.0.1340/flink.js (2)
W/art: Attempt to remove non-JNI local reference, dumping thread
```

###### Dependencies Grep
```
+--- com.plaid.link:sdk-core:3.10.0
+--- com.plaid.link:sdk-core:{strictly 3.10.0} -> 3.10.0 (c)
```

**Comment by antonPolosin** [comment]
@amytang0 any updates on this issue. trying to use 3.9.0 Plaid sdk and still facing the same issue. Plaid link flow is failing to open on  api level 24 and 21?

**Comment by phoenixy1** [comment]
I am closing out this issue as the 3.x SDK is no longer supported and there have been no reports of customers experiencing this on the 4.x  or later SDKs. If this is happening on later SDKs, feel free to comment in this thread or create a new issue.
