### ISSUE TITLE
Link with account numbers option not showing

### ISSUE THREAD

**Issue by praveen-kanwar** [plaid/plaid-link-android#233]
# The problem

Link With Account Number {Which was shown previously at the bottom} is replaced with "Don't see your institution? Search Instead" Option is coming

https://user-images.githubusercontent.com/2133961/184619884-59a0961d-20d8-4613-8ab1-69e554a6cace.jpeg

**Comment by phoenixy1** [comment]
@praveen-kanwar This field may or may not show up depending on how Link is configured with the link token. Can you provide the details of the parameters you're sending in the `/link/token/create` request? (omitting any that contain sensitive data, of course)

**Comment by praveen-kanwar** [comment]
Thanks, @phoenixy1 for the quick support was able to resolve the issue.
