### ISSUE TITLE
Missing release notes for latest release 3.11.0

### ISSUE THREAD

**Issue by eric-labelle** [plaid/plaid-link-android#243]
# The problem

The version `3.11.0` was [released last week](https://central.sonatype.com/artifact/com.plaid.link/sdk-core/3.11.0/versions) but there are still no release notes available on https://github.com/plaid/plaid-link-android/releases

**Comment by melissaosullivan** [comment]
@eric-labelle The release notes for `3.11.0` have now been added. Thanks for pointing this out.
