### ISSUE TITLE
Plaid SDK introduces high and medium security vulnerabilities from com.google.protobuf dependency

### ISSUE THREAD

**Issue by dmytroKarataiev** [plaid/plaid-link-android#244]
# The problem

Snyk security check found three security vulnerabilities in the Plaid 3.10-3.11 SDKs:
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-3167771
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-3040281
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-3040280

# Expected Result
Security vulnerabilities have been fixed in the following dependencies:
Upgrade com.google.protobuf:protobuf-javalite to version 3.16.3, 3.19.6, 3.20.3, 3.21.7 or higher.
Upgrade com.google.protobuf:protobuf-kotlin-lite to version 3.16.3, 3.19.6, 3.20.3, 3.21.7 or higher.

**Comment by phoenixy1** [comment]
This has since been fixed in the latest builds of the 4.x and 5.x versions (3.x is no longer officially supported).
