### ISSUE TITLE
PlaidLinkConfigurationInvalidTokenException in version 0.3.4 while reconnecting account.

### ISSUE THREAD

**Issue by hitesh-banknovo** [plaid/plaid-link-android#26]
I got the error while reconnecting the existing plaid account. The error is **The public token provided is not formatted correctly** at **

> com.plaid.linkbase.models.PlaidLinkConfigurationInvalidTokenException

**

**Comment by zsweigart** [comment]
Thanks for the report, we have fixed the issue and will push it out with the next release.

**Comment by zsweigart** [comment]
We have pushed a fix 0.3.5 for this issue
