### ISSUE TITLE
The Jacoco plugin extension version '0.8.9' is not currently available in the Android Gradle Plugin. Setting the version to 0.8.8

### ISSUE THREAD

**Issue by xrafi** [plaid/plaid-link-android#263]
# The problem

Hello - when we updated Plaid SDK from 3.13.2 to 4.1.1
With no other changes - im getting this error - when unit tests are being executed on buildkite

 `The Jacoco plugin extension version '0.8.9' is not currently available in the Android Gradle Plugin. Setting the version to 0.8.8`

Android Studio Hedgehog | 2023.1.1 Patch 2
Build #AI-231.9392.1.2311.11330709, built on January 18, 2024
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    detekt (2.3.0)
    com.robohorse.robopojogenerator (2.4.2)
    PythonCore (231.9225.4)

**Comment by meghandaly** [comment]
Full disclosure, I am not affiliated with `plaid`, but it doesn't look like this is their issue, see Google issues: [Unable to set JaCoCo version in AGP 8.2.0](https://issuetracker.google.com/issues/298703884) and [Warning spam: Jacoco plugin extension version '0.8.9' is not currently available](https://issuetracker.google.com/issues/324271174).

**Comment by phoenixy1** [comment]
Closed as third party issue, see linked issue
