### ISSUE TITLE
Plaid 4.2.0 on maven but no release info on github?

### ISSUE THREAD

**Issue by jt-gilkeson** [plaid/plaid-link-android#265]
Self explanatory - the readme shows maven-central v.4.2.0 is the latest release yet the codebase has 4.1.1 as the latest - what is in 4.2.0?  Are there any breaking, changes, etc?

**Comment by melissaosullivan** [comment]
Release notes are here: https://github.com/plaid/plaid-link-android/releases/tag/v4.2.0.

Thanks!
