### ISSUE TITLE
Sdk version is out-dated in sample project

### ISSUE THREAD

**Issue by ergindogan** [plaid/plaid-link-android#35]
SDK version in [build.gradle](https://github.com/plaid/plaid-link-android/blob/master/app/build.gradle#L38) is out dated. I am getting compilation error right now. Updating it to `1.0.0` fixes the issue.

**Comment by zsweigart** [comment]
Fixed! Thanks for pointing that out! https://github.com/plaid/plaid-link-android/pull/36
