### ISSUE TITLE
Issues updating from SDK 1.0.3 -> 1.1.0

### ISSUE THREAD

**Issue by mictab** [plaid/plaid-link-android#43]
Hi,

We're experiencing issues updating from SDK 1.0.3 to 1.1.0. More specifically, we cannot access `LinkEventMetadata` anymore without errors. Just to verify I tried to access it in the sample app provided in this repository and I get the same issue (see attached image):

<img width="791" alt="Screenshot 2020-03-17 at 11 11 56" src="https://user-images.githubusercontent.com/11392811/76846219-73e7fb00-6840-11ea-9c07-04c9b1e3dbd0.png">

Any ideas? It is working fine in 1.0.3.

**Comment by zsweigart** [comment]
Hi @mictab It looks like our proguard rules were too aggressive, we'll put out a patch as soon as possible

**Comment by JeroenMols** [comment]
We were able to identify and fix this issue, going through internal review and testing now. Will let you know when we have a new release.

**Comment by mictab** [comment]
Great, thank you for the quick response and action.

**Comment by zsweigart** [comment]
1.2.0 has been released!
