### ISSUE TITLE
Fabric crash report: KotlinNullPointerException at com.plaid.link.internal.root.LinkRootInteractor.refreshDataFromServer + 242(LinkRootInteractor.java:242)

### ISSUE THREAD

**Issue by hitesh-banknovo** [plaid/plaid-link-android#47]
- Plaid SDK version 1.0.0
- Fabric crash report:

> #0. Crashed: main
>        at com.plaid.link.internal.root.LinkRootInteractor.refreshDataFromServer + 242(LinkRootInteractor.java:242)
>        at com.plaid.link.internal.root.LinkRootInteractor.didBecomeActive + 111(LinkRootInteractor.java:111)
>        at com.plaid.ribs.Interactor.dispatchAttach$ribs_release + 48(Interactor.java:48)
>        at com.plaid.ribs.ViewInteractor.dispatchViewAttach$ribs_release + 15(ViewInteractor.java:15)
>        at com.plaid.ribs.Router.dispatchAttach$ribs_release + 85(Router.java:85)
>        at com.plaid.ribs.android.RibActivity.onFragmentReady + 155(RibActivity.java:155)
>        at com.plaid.link.internal.LinkActivity.onFragmentReady + 76(LinkActivity.java:76)
>        at com.plaid.ribs.android.DependencyFragment.onActivityCreated + 28(DependencyFragment.java:28)
>        at androidx.fragment.app.Fragment.performActivityCreated + 2619(Fragment.java:2619)
>        at androidx.fragment.app.FragmentManagerImpl.moveToState + 904(FragmentManagerImpl.java:904)
>        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState + 1238(FragmentManagerImpl.java:1238)
>        at androidx.fragment.app.FragmentManagerImpl.moveToState + 1303(FragmentManagerImpl.java:1303)
>        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange + 2659(FragmentManagerImpl.java:2659)
>        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated + 2613(FragmentManagerImpl.java:2613)
>        at androidx.fragment.app.FragmentController.dispatchActivityCreated + 246(FragmentController.java:246)
>        at androidx.fragment.app.FragmentActivity.onStart + 542(FragmentActivity.java:542)
>        at androidx.appcompat.app.AppCompatActivity.onStart + 201(AppCompatActivity.java:201)
>        at com.plaid.ribs.android.LifecycleActivity.onStart + 55(LifecycleActivity.java:55)
>        at android.app.Instrumentation.callActivityOnStart + 1395(Instrumentation.java:1395)
>        at android.app.Activity.performStart + 7356(Activity.java:7356)
>        at android.app.ActivityThread.handleStartActivity + 3159(ActivityThread.java:3159)
>        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence + 180(TransactionExecutor.java:180)
>        at android.app.servertransaction.TransactionExecutor.cycleToPath + 165(TransactionExecutor.java:165)
>        at android.app.servertransaction.TransactionExecutor.executeLifecycleState + 142(TransactionExecutor.java:142)
>        at android.app.servertransaction.TransactionExecutor.execute + 70(TransactionExecutor.java:70)
>        at android.app.ActivityThread$H.handleMessage + 1969(ActivityThread.java:1969)
>        at android.os.Handler.dispatchMessage + 106(Handler.java:106)
>        at android.os.Looper.loop + 214(Looper.java:214)
>        at android.app.ActivityThread.main + 7124(ActivityThread.java:7124)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
>        at com.android.internal.os.ZygoteInit.main + 975(ZygoteInit.java:975)
> 
> --
> 
> Fatal Exception: kotlin.KotlinNullPointerException
>        at com.plaid.link.internal.root.LinkRootInteractor.refreshDataFromServer + 242(LinkRootInteractor.java:242)
>        at com.plaid.link.internal.root.LinkRootInteractor.didBecomeActive + 111(LinkRootInteractor.java:111)
>        at com.plaid.ribs.Interactor.dispatchAttach$ribs_release + 48(Interactor.java:48)
>        at com.plaid.ribs.ViewInteractor.dispatchViewAttach$ribs_release + 15(ViewInteractor.java:15)
>        at com.plaid.ribs.Router.dispatchAttach$ribs_release + 85(Router.java:85)
>        at com.plaid.ribs.android.RibActivity.onFragmentReady + 155(RibActivity.java:155)
>        at com.plaid.link.internal.LinkActivity.onFragmentReady + 76(LinkActivity.java:76)
>        at com.plaid.ribs.android.DependencyFragment.onActivityCreated + 28(DependencyFragment.java:28)
>        at androidx.fragment.app.Fragment.performActivityCreated + 2619(Fragment.java:2619)
>        at androidx.fragment.app.FragmentManagerImpl.moveToState + 904(FragmentManagerImpl.java:904)
>        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState + 1238(FragmentManagerImpl.java:1238)
>        at androidx.fragment.app.FragmentManagerImpl.moveToState + 1303(FragmentManagerImpl.java:1303)
>        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange + 2659(FragmentManagerImpl.java:2659)
>        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated + 2613(FragmentManagerImpl.java:2613)
>        at androidx.fragment.app.FragmentController.dispatchActivityCreated + 246(FragmentController.java:246)
>        at androidx.fragment.app.FragmentActivity.onStart + 542(FragmentActivity.java:542)
>        at androidx.appcompat.app.AppCompatActivity.onStart + 201(AppCompatActivity.java:201)
>        at com.plaid.ribs.android.LifecycleActivity.onStart + 55(LifecycleActivity.java:55)
>        at android.app.Instrumentation.callActivityOnStart + 1395(Instrumentation.java:1395)
>        at android.app.Activity.performStart + 7356(Activity.java:7356)
>        at android.app.ActivityThread.handleStartActivity + 3159(ActivityThread.java:3159)
>        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence + 180(TransactionExecutor.java:180)
>        at android.app.servertransaction.TransactionExecutor.cycleToPath + 165(TransactionExecutor.java:165)
>        at android.app.servertransaction.TransactionExecutor.executeLifecycleState + 142(TransactionExecutor.java:142)
>        at android.app.servertransaction.TransactionExecutor.execute + 70(TransactionExecutor.java:70)
>        at android.app.ActivityThread$H.handleMessage + 1969(ActivityThread.java:1969)
>        at android.os.Handler.dispatchMessage + 106(Handler.java:106)
>        at android.os.Looper.loop + 214(Looper.java:214)
>        at android.app.ActivityThread.main + 7124(ActivityThread.java:7124)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
>        at com.android.internal.os.ZygoteInit.main + 975(ZygoteInit.java:975)

**Comment by amytang0** [comment]
Hi, does this repro with 1.2.1?

**Comment by JeroenMols** [comment]
@maxdjohnson We've made quite a few improvements in the area around were the crash occurs, could you please see if this happens with 1.2.1?

**Comment by JeroenMols** [comment]
Closing this issue as no response received within 30 days

**Comment by hitesh-banknovo** [comment]
It is fixed in 1.2.1. Thanks.
