### ISSUE TITLE
Cannot detect a click on the "Connect" button

### ISSUE THREAD

**Issue by remvst** [plaid/plaid-link-android#50]
I'm currently working on the Android version of a product where we'd like to take our users to a manual connect flow in case they don't find their institution, and click the "Connect" button.

On the latest version (`1.2.1`), it seems like clicking on the "Connect" button gives us a cancellation status of `institution_not_found`, which is the same status as if they clicked on the close (X) button when the list of results is empty.

Is there a way to differentiate these two button clicks? And if not, could we submit a feature request?

**Comment by amytang0** [comment]
Hi, in the case where we don't support the institution, we do offer a micro-deposits flow to check the account number directly https://plaid.com/docs/#auth . Does that work for your situation?

**Comment by remvst** [comment]
@amytang0 thank you for the quick reponse :) 

We do already have our own custom micro deposits flow built and shipped to users, we're just looking to take our users to it whenever they click that "Connect" button (which currently does nothing).
I don't think we'll be looking into rebuilding the manual bank linking flow any time soon, so this wouldn't work for us.

**Comment by amytang0** [comment]
I'm curious where the "Connect" button is showing for an institution that your users can't find? Would you mind explaining the repro steps (might be a bug on our end)?

**Comment by remvst** [comment]
@amytang0 here is a quick recording of what we're seeing (from our actual app, not the example one)

![plaid-upgrade](https://user-images.githubusercontent.com/3472387/78940688-462f5400-7a84-11ea-81bb-f06d5e5c7123.gif)

As you can see on the GIF, I'm seeing the "connect" button as soon as I start typing something.

The exit values that I'm seeing are the following:

User searches for “chase” (list of results isn’t empty):
    - close button cancellation status = requires_credentials
    - connect button cancellation status = institution_not_found

User searches for “chasef” (list of results is empty):
    - close button cancellation status = institution_not_found
    - connect button cancellation status = institution_not_found

**Comment by amytang0** [comment]
Nice, thank you for the video! What is your LinkConfiguration (exclude sensitive information like token)?

**Comment by remvst** [comment]
```kotlin
    override fun navigateToPlaidLink(userLegalName: String, userEmailAddress: String) {
        Plaid.openLink(
            activity,
            LinkConfiguration(
                clientName = activity.getString(R.string.app_name),
                products = listOf(PlaidProduct.AUTH),
                userLegalName = userLegalName,
                userEmailAddress = userEmailAddress
            ),
            REQUEST_CODE_PLAID
        )
    }
```

and our options:
```kotlin
        val plaidOptions = PlaidOptions(
            logLevel = if (BuildConfig.DEBUG) LogLevel.VERBOSE else LogLevel.ASSERT,
            environment = when (BuildConfig.FLAVOR) {
                "prod" -> PlaidEnvironment.PRODUCTION
                else -> PlaidEnvironment.SANDBOX
            }
        )
        Plaid.setOptions(plaidOptions)
```
The GIF above was recorded on a debug build (therefore sandbox environment).

**Comment by amytang0** [comment]
Sorry for the many questions, and what happens when you click on Connect? That should take you through our microdeposits flow

**Comment by remvst** [comment]
No worries. When I click the button, it always exits the Plaid activity and resumes our activity, with the activity result I mentioned above. I've never seen it take me to the microdeposits flow, in prod or in debug. 

If it gets fixed we'll definitely want to disable that though, since we already have our own microdeposits flow set up (with a custom screen and API)

**Comment by amytang0** [comment]
Hi, I talked to our product team and unfortunately we are discouraging custom user flows. I see that your team does not have the microdeposits flow enabled and would encourage you to talk to your account manager about those.
