### ISSUE TITLE
Status bar colour

### ISSUE THREAD

**Issue by empowerCassie** [plaid/plaid-link-android#58]
In the linking activity it would be nice if the status bar colour was set to the branding of the institution the user is linking. The full screen of colour looks a little odd with a white status bar on top.

**Comment by zsweigart** [comment]
Hi @empowerCassie thanks for the feedback. Unfortunately we do not currently support changing the color of the status bar and do not plan to change it in the near future.

**Comment by empowerCassie** [comment]
Just to clarify I wasn't asking for a way for us to set the status bar colour. Just suggesting that it should also be set to improve the overall look of the plaid activity.
