### ISSUE TITLE
Filtering account subtypes

### ISSUE THREAD

**Issue by remvst** [plaid/plaid-link-android#60]
I am currently working on an app that uses the Android Link SDK, and I noticed that the Javascript SDK allows filtering checking and savings accounts:
```js
var handler = Plaid.create({
  accountSubtypes: {
    depository: ['checking', 'savings'],
  },
  ...
});
```
(found at https://plaid.com/docs/ )

Is there a way to enable the same filters on the Android SDK? I couldn't find anything in `LinkConfiguration`

Our use case is that we only want to allow the user to select a checking or savings account.

If such a filter is enabled by default, we would still like to explicitly set it on the client (for code clarity).

**Comment by zsweigart** [comment]
Hi @remvst we currently don't have accountSubtype filtering as part of the LinkConfiguration object; however, we are working on adding it in a future release.  Please reach out to your Plaid account manager for more information.
