### ISSUE TITLE
How to start linking with specific institution without showing institution picker 

### ISSUE THREAD

**Issue by LukaFinzgar** [plaid/plaid-link-android#67]
Greetings!

I would like to add parameter to LinkConfiguration object to start linking with specific institution instead of showing inst./bank picker when Plaid.openLink(....) is called. 
I can't find anything like this in the docs. 

In ios sdk, i found this function:
http://cocoadocs.org/docsets/Plaid/1.0.4/Classes/PLKPlaidLinkViewController.html#//api/name/initWithInstitution:delegate:

Is this possible with plaid link android?

Thank you.

**Comment by Beat-O** [comment]
Sent to Caroline.

**Comment by zsweigart** [comment]
Hi @LukaFinzgar 
This method has been deprecated and we suggest you use the full link flow.  If you have more questions please reach out to your account manager and they can provide more details.
