### ISSUE TITLE
IllegalStateException on Plaid#openLink

### ISSUE THREAD

**Issue by eddiecrawford** [plaid/plaid-link-android#71]
Hello! 

We are currently trying to bump our Plaid version to `1.4.1`. 
Upon starting the plaid flow at runtime via `Plaid.openLink` with a valid configuration set, link event listener set, and public key set in our application manifest, we receive this stack trace:

<details>
    <summary> Stack Trace </summary>

```
06-02 10:32:05.901  2030  3039 I ActivityTaskManager: START u0 {flg=0x4000000 cmp=com.ibotta.android/com.plaid.link.internal.LinkActivity} from uid 10134
06-02 10:32:06.269  1877  1877 I keystore: del USRPKEY_plaid_encryption_key 10134
06-02 10:32:06.269  1877  1877 I keystore: del USRSKEY_plaid_encryption_key 10134
06-02 10:32:06.269  1877  1877 I keystore: del USRCERT_plaid_encryption_key 10134
06-02 10:32:06.270  1877  1877 I keystore: del CACERT_plaid_encryption_key 10134
06-02 10:32:06.313 12860 13363 I AndroidKeysetManager: cannot read keyset: java.io.IOException: can't read keyset; the pref value plaid_encryption_keyset does not exist
06-02 10:32:06.909 12860 12860 E j3$d    : java.lang.IllegalStateException:
06-02 10:32:06.909 12860 12860 E j3$d    : 	at com.plaid.j3$h.accept(SourceFile:21)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at io.reactivex.internal.operators.single.SingleDoOnEvent$DoOnEvent.onSuccess(SingleDoOnEvent.java:55)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at android.os.Handler.handleCallback(Handler.java:883)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at android.os.Looper.loop(Looper.java:214)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at android.app.ActivityThread.main(ActivityThread.java:7356)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at java.lang.reflect.Method.invoke(Native Method)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-02 10:32:06.909 12860 12860 E j3$d    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
06-02 10:32:06.909 12860 12860 E j3$d    :
06-02 10:32:06.920  2030  6402 W ActivityTaskManager: Duplicate finish request for ActivityRecord{75621e9 u0 com.ibotta.android/com.plaid.link.internal.LinkActivity t154 f}
```

</details>

My first inkling is something to do with any of the `rx` or `androidx.work` libraries, however our application is on the same version of these dependencies as the Plaid Link `1.4.1` SDK. Even upon a gradle build scan, I see no dependency conflicts or anything that may stand out.

The stack trace is unfortunately too ambiguous for us to debug. Hopefully there is something we could be missing and your awesome team can do to help us with this production issue! Thoughts?

**Comment by zsweigart** [comment]
Hi @eddiecrawford thanks for the report!
Could you please provide the following information:

1. What device(s)/emulator(s) are you using
2. What os versions are they on?
3. What are the steps to reproduce
4. What is your Link configuration (don't forget to omit your key)
5. How often is this reproducible

**Comment by eddiecrawford** [comment]
Hi! Thank you for responding 🙏 

1. Pixel 3 -- (Emulator)
2. API 29
3. Steps:
  - We have a CTA on an Activity that calls this logic:
```
        Plaid.setLinkEventListener { connectionListener.onACHConnectionEvent(it) }
        Plaid.openLink(activity, configuration, REQ_CODE)
```
  - Hard crash right after
4. Config:
  ```
        LinkConfiguration(
            clientName = "Ibotta",
            products = listOf(PlaidProduct.AUTH, PlaidProduct.ASSETS),
            environment = PlaidEnvironment.PRODUCTION
        )
```
  - Android Manifest in Application Tag:
```
        <meta-data android:name="com.plaid.link.public_key" android:value="@string/plaid_api_key" />

```

5. Every time =/

**Comment by zsweigart** [comment]
Hi @eddiecrawford, it seems we created a bug while working on our June release.  A work-around  for 1.4.1 is to add
```
Plaid.setOptions(PlaidOptions(environment = PlaidEnvironment.PRODUCTION))
```
In samples we usually use
```
Plaid.setOptions(PlaidOptions(environment = if (BuildConfig.DEBUG) PlaidEnvironment.SANDBOX else  PlaidEnvironment.PRODUCTION))
```

However, the June release will be a 2.0.0 breaking change and PlaidOptions will be removed entirely.

I'll leave this issue open until we release 2.0.0 with updated documentation.

Thanks!

**Comment by zsweigart** [comment]
I plugged your configuration it into our sample app (with our own key) and everything ran fine on a Pixel 3 emulator with Android 29. 

Have you tried clearing the storage or doing a clean install since adding the line?

**Comment by zsweigart** [comment]
Also 2.0.0-rc1 has been published

**Comment by eddiecrawford** [comment]
Yup! Clean everything. I have an inkling there is some sort of conflict between either an androidx dependency or rx library. We'll give the new RC a shot!

**Comment by eddiecrawford** [comment]
Do you all have any available documentation for your 2.0 RC?
Trying to fill in the gaps from what I see in the readable source, but think I'm missing something with how the public key works :)

**Comment by zsweigart** [comment]
Hi @eddiecrawford we have not updated the docs yet, but we have a PR showing the migration https://github.com/plaid/plaid-link-android/pull/66

**Comment by ahclipse** [comment]
Following up here; we utilized the `2.0.0` release and were able to get this working. 

The version bump and conforming to the breaking changes fixed the original problem. We also had to re-register our package name on the dashboard. 

Thanks for the quick responses!
