### ISSUE TITLE
Calling token instead of publicKey in openLink() function throws INVALID_FIELD. 

### ISSUE THREAD

**Issue by nickwjmz** [plaid/plaid-link-android#78]
With the new "com.plaid.link:sdk-core:2.0.0" dependency, when integrating with Link on the Android Studio (4.0) emulated device, the attempt fails with INVALID_FIELD on the first attempt. This only happens when using the 'token' variable instead of 'publicKey'. 

Android Studio gives me the "deprecated" warning when I use 'publicKey' so I tried using the new 'token' variable instead, but the link attempt fails every time. 

<img width="695" alt="Screen Shot 2020-06-16 at 8 43 56 PM" src="https://user-images.githubusercontent.com/57211842/84845367-1b2c2800-b012-11ea-90a2-df64028ccca7.png">

The project works with no problems when commenting out the 'token' line and uncommenting 'publicKey' so I am just doing that for now.

**Comment by zsweigart** [comment]
Hi @nickwjmz there are two ways to integrate with Plaid - a public key or tokens.  They have different formats so if you are using a public key you should continue to pass it into the `publicKey` field.

We will be moving away from public key to tokens in the near future but you can read more about it here https://plaid.com/docs/link-token-migration-guide/

The token field is also used for access tokens for update mode.

**Comment by nickwjmz** [comment]
Ok, after opening this I had went back and reread the Link integration docs and realized the `token` field was for update mode but I left it up because there was no mention of the `public-key` deprecation. But I see now from your link that I wasn't looking in the right spot. Thank you!
