### ISSUE TITLE
LinkAccount returning null accountType and accountSubType

### ISSUE THREAD

**Issue by pkSurkus** [plaid/plaid-link-android#8]
Android sdk is returning accountType=null, accountSubType=null, verificationStatus=null for all the accounts being returned for product Auth, environment SANDBOX,  user_good, pass_good

**Comment by amytang0** [comment]
Hi Pawan, thank you for reporting this bug, we are looking into this now

**Comment by zsweigart** [comment]
Hi Pawan,  this has been fixed in 0.3.0 which has been released
