### ISSUE TITLE
error code INVALID_FIELD after calling Plaid.openLink()

### ISSUE THREAD

**Issue by RichieZhu26** [plaid/plaid-link-android#81]
Hello! I ran the example project for Android plaid link and it worked fine on my Android emulator. However when I tried to integrate the code into my own project I received the error code INVALID_FIELD after calling Plaid.openLink(). I didn't change any part of the code, except for the name of the files and clientName. I've already added the package name to my Plaid dashboard and the public_key should also be correct. I'm using the 2.0.0 version. Thanks in advance!!!

![Screen Shot 2020-06-24 at 22 46 31](https://user-images.githubusercontent.com/45186031/85647880-7d69d600-b66d-11ea-89d4-8e6fb288c933.png)

![Screen Shot 2020-06-24 at 22 47 35](https://user-images.githubusercontent.com/45186031/85647905-865aa780-b66d-11ea-9996-5bb54d4734d8.png)

![Screen Shot 2020-06-24 at 22 47 58](https://user-images.githubusercontent.com/45186031/85647944-9bcfd180-b66d-11ea-8b2a-3f40361e641a.png)

**Comment by amytang0** [comment]
Hey Richie,

I'm curious, for your internal project, are you using Proguard (i.e. `minifyEnabled true`? Would it be possible to share your project (or this snippet) to help repro?

Thank you,
Amy

**Comment by RichieZhu26** [comment]
Hi! I attached the related snippet (I think the answer is no?)

![Screen Shot 2020-06-25 at 12 22 05](https://user-images.githubusercontent.com/45186031/85758671-8b0b7400-b6de-11ea-95ef-942d46666fbe.png)

**Comment by RichieZhu26** [comment]
Is there anything else I should provide to make my issue clearer? Thank you again!

**Comment by amytang0** [comment]
Thanks for checking the proguard settings, it doesn't look like this is affecting things.

If possible, it would be great to get your project code or sample project code where this repros. 

Thank you!
Amy

**Comment by RichieZhu26** [comment]
Solved. It turned out that the package_name was defined twice in the project.
