### ISSUE TITLE
Android app with Plaid SDK crashes on few phones  with Okhttp3 error

### ISSUE THREAD

**Issue by akshaymanathkar** [plaid/plaid-link-android#83]
My Android app has Native Android as well as react native code. When someone is going to ReactNative section of my app, it is crashing for few people mostly Samsung phones. Following are the version currently I am using 
Plaid SDK 1.2.0
okhttp3: 3.11.0
'com.facebook.react:react-native:+'

Fatal Exception: java.lang.NoSuchMethodError
No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in base.apk!classes5.dex)
okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies (JavaNetCookieJar.java:91)
okhttp3.JavaNetCookieJar.loadForRequest (JavaNetCookieJar.java:74)
com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest (ReactCookieJarContainer.java:49)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:74)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:74)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:100)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:197)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:502)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)

This started happening since I included Plaid SDK to my Android App

**Comment by zsweigart** [comment]
Hi @akshaymanathkar We have a separate RN sdk that may be helpful for you.  https://github.com/plaid/react-native-plaid-link-sdk This will also require you to update you okhttp3 version to >= `4.0.0`

If please update to the Plaid Link SDK version `2.0.0` and your okhttp3 version to >= `4.0.0`

**Comment by akshaymanathkar** [comment]
> Hi @akshaymanathkar We have a separate RN sdk that may be helpful for you. https://github.com/plaid/react-native-plaid-link-sdk This will also require you to update you okhttp3 version to >= `4.0.0`
> 
> If please update to the Plaid Link SDK version `2.0.0` and your okhttp3 version to >= `4.0.0`

@zsweigart  I don't need RN SDK as I use react native just for specific feature. All other payment code is in Kotlin. I tried upgrading SDK to `2.0.0` still see same problem

**Comment by zsweigart** [comment]
Hi @akshaymanathkar have you tried updating Okhttp3 to a version >= `4.0.0`

**Comment by akshaymanathkar** [comment]
> Hi @akshaymanathkar have you tried updating Okhttp3 to a version >= `4.0.0`

I tried upgrading it to 4.0.0 but my doubt is React native is using 3.X version of okhttp3 and that is conflicting with this

**Comment by zsweigart** [comment]
Yes, RN defaults to 3.12 but you can override them by adding
```
    implementation "com.squareup.okhttp3:okhttp:4.2.1"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:4.2.1"
```

**Comment by sonbach** [comment]
I work with @akshaymanathkar and we've tried
`implementation 'com.squareup.okhttp3:okhttp:4.8.0'`

We don't need `com.squareup.okhttp3:okhttp-urlconnection` so I didn't add 
`implementation "com.squareup.okhttp3:okhttp-urlconnection:4.2.1"`

After upgrading to 4.8.0 for okhttp and to Plaid 1.4.1, the amount of users experiencing the crash decreased, but there are still some.  Users spanning many devices running on several different versions of Android.
`implementation 'com.plaid.link:sdk-core:1.4.1'`

**Comment by JeroenMols** [comment]
Thanks for reporting. 

Since we haven't heard back from you in a while, we are assuming this no longer is an issue for you. Please don't hesitate to reopen/file a new issue should this issue still persist on the latest SDK version.
