### ISSUE TITLE
LinkConfiguration validation error in 2.0.0

### ISSUE THREAD

**Issue by mictab** [plaid/plaid-link-android#85]
Hi! We've started to see this crash since upgrading to version 2.0.0.

```
Caused by com.plaid.link.internal.exceptions.PlaidLinkConfigurationMissingAuthorizationException
Either publicKey or a token must be provided

com.plaid.link.configuration.LinkConfiguration$Builder.validateConfiguration (LinkConfiguration.java:41)
com.plaid.link.configuration.LinkConfiguration$Builder.build (LinkConfiguration.java:1)
com.plaid.link.PlaidKotlinFunctionsKt.linkConfiguration (PlaidKotlinFunctionsKt.java:1)
```

We're initialising Plaid Link like so:

```kotlin
openPlaidLink(
        linkConfiguration = linkConfiguration {
            clientName = CLIENT_NAME
            products = listOf(PlaidProduct.TRANSACTIONS)
            token = plaidToken
            language = Locale.ENGLISH.language
            countryCodes = listOf(Locale.US.country)
            logLevel = if (BuildConfig.DEBUG) {
                LinkLogLevel.VERBOSE
            } else {
                LinkLogLevel.ASSERT
            }
            environment = plaidEnvironment
        }
)
```

Where `plaidToken` is either a public token, item add token or null. Any ideas about what's going wrong?

**Comment by zsweigart** [comment]
Hi @mictab that configuration looks correct.  The `PlaidLinkConfigurationMissingAuthorizationException` is only thrown when `token` is null and `publicKey` is null.  Could you try logging your variable `plaidToken` to see if the value is null?

**Comment by mictab** [comment]
Thanks for the reply @zsweigart. It seems like I can reproduce the crash by passing in `token = null` (which would be the case whenever we fail to generate an item-add-token). Setting the `publicKey` value seems to prevent the crash in these cases. I noticed that `publicKey` has been marked as deprecated though. Is it safe to always pass in the `publicKey` value?

**Comment by zsweigart** [comment]
It is safe to use `publicKey`.  `item-add-token` is an alternative way to initialize link that works with `publicKey`.  We marked `publicKey` deprecated in this release as a new tokenized method for initializing link will be available soon, but there have been some slight delays so keep an eye out for that announcement.
