### ISSUE TITLE
When every i add implementation'com.plaid.link:sdk-core:2.1.0' in android project i get error

### ISSUE THREAD

**Issue by naimishmodi39** [plaid/plaid-link-android#87]
error: cannot access HasFragmentInjector
public abstract class BaseActivity<T extends ViewDataBinding, V extends BaseViewModel> extends DaggerAppCompatActivity implements HasSupportFragmentInjector,BaseFragment.Callback, UtilClass.AlertMenuListener {
^
class file for dagger.android.HasFragmentInjector not found

in any android project in java language that use dependency injection have the issue after adding this library

**Comment by amytang0** [comment]
Hi Naimish,
What version of link-sdk are you using? Can you also include your Dagger Gradle dependency?

Thank you!
Amy

**Comment by naimishSilicon** [comment]
Hi Amy,
Thank you for respond
This are the Dagger library and annotationProcessor  that i use 

    implementation 'com.google.dagger:dagger:2.21'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.21'
    implementation 'com.google.dagger:dagger-android-support:2.21'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.21'

**Comment by naimishmodi39** [comment]
Hi Amy,
Thank you for reply
This are the Dagger library and annotationProcessor that i use

implementation 'com.google.dagger:dagger:2.21'
annotationProcessor 'com.google.dagger:dagger-compiler:2.21'
implementation 'com.google.dagger:dagger-android-support:2.21'
annotationProcessor 'com.google.dagger:dagger-android-processor:2.21'

**Comment by amytang0** [comment]
Interesting, so I tried to replicate the issue in a sample project and did not run across this error. How are you using Dagger in your project/ where are you injecting?

**Comment by naimishmodi39** [comment]
try this demo project to replicate the issue

https://github.com/MindorksOpenSource/android-mvvm-architecture

**Comment by amytang0** [comment]
Thank you for providing the sample project. 
So [`dagger.android.HasFragmentInjector`does not exist in `2.24`](https://github.com/google/dagger/commit/3bd8f707cb28fd0c5f3abb4f87658566f8b52c10), but does exist in the sample Mindorks project you sent me: `2.16` and `2.21`, the version you are using. Internally, Plaid is currently using `2.27`, so when you pulled in the Plaid Link SDK, it was also pulling in the `2.27` Dagger2 dependency (which uses `HasAndroidInjector` instead).

You have two possible solutions: 
1. Upgrade to Dagger2:2.24+
2. Pull in the Plaid library without the Dagger dependency like:
```
    implementation("com.plaid.link:sdk-core:2.1.0") {
        exclude group:  "com.google.dagger", module: "dagger-android"
    }
```

Let me know if that fixes your issue!

**Comment by amytang0** [comment]
Closing after 30 days of inactivity
