### ISSUE TITLE
Issue with iOS SDK

### ISSUE THREAD

**Issue by ioskunal** [plaid/plaid-link-android#97]
Since the iOS Repo does not contain /issues section, Unfortunately I have to create an issue here.

I recently updated my iOS SDK from 1.1.33 to 2.0.1 using **CocoaPods** but it does not work. 
The classes like `PLKPlaidLinkViewController` , `PLKPlaidLinkViewDelegate` are not recognised and I receive an error `Use of undeclared type 'PLKPlaidLinkViewController'` . 

As soon as I downgrade to version 1.1.33, clean it and rebuild, it works like charm. Can you please assign this to someone who can have a look at this issue. 

Also please find a  way to add /issues for iOS Repo.

**Comment by afh** [comment]
Thanks for reaching out @ioskunal, in the future please file issues for the Plaid Link iOS SDK through the [dashboard](https://dashboard.plaid.com/support/new). 

Please have a look at the [`main-v2`](https://github.com/plaid/plaid-link-ios/tree/main-v2) branch of the iOS project specifically [`ViewController+LinkToken.swift`](https://github.com/plaid/plaid-link-ios/blob/main-v2/LinkDemo-Swift/LinkDemo-Swift/ViewController%2BLinkToken.swift) when doing link token based account linking, and [`ViewController+PublicKey.swift`](https://github.com/plaid/plaid-link-ios/blob/main-v2/LinkDemo-Swift/LinkDemo-Swift/ViewController%2BPublicKey.swift) for compatibility with LinkKit 1.x public key based account linking.

Also review the [Plaid documentation](https://plaid.com/docs/link/ios/) that will be updated in the coming days.

**Comment by afh** [comment]
@ioskunal In case you are still running into issues with LinkKit 2.0.1 please see the Plaid Link iOS [1.x to 2.x Migration Guide](https://plaid.com/docs/link/ios/ios-v2-migration/).

**Comment by ioskunal** [comment]
Thanks @afh That helped a lot 👍

**Comment by afh** [comment]
Glad to hear that @ioskunal, following up with another update to the [Plaid Link for iOS docs](https://plaid.com/docs/link/ios/).
