### ISSUE TITLE
Problem with usage on fragment

### ISSUE THREAD

**Issue by NirmalyaSin** [plaid/plaid-link-android#98]
I am using version 2. When using it from fragment after bank link I cannot get the link results in my fragment.

**Comment by amytang0** [comment]
Hi, can you upgrade to the latest version and see if this issue still occurs? 3.0.1

**Comment by NirmalyaSin** [comment]
Okay I will but I don't see any way to get the bank account number in 3.0.1. Can you tell how to achieve that ?

**Comment by DrGreyManAfreeMASONG7** [comment]
https://opalgroup.net/conference/real-estate-investment-summit-2020/

**Comment by JeroenMols** [comment]
Hi @NirmalyaSin,

Is there anything we could still help you with in resolving this issue?

**Comment by NirmalyaSin** [comment]
No it's okay! Thank you so much for your help.

**Comment by JeroenMols** [comment]
Glad you were able to sort this out, well done!
Thanks for filing this issue, proceeding with closing it now.
